### ISSUE TITLE
Digitalstrom Eltako Multisensor via Enocean

### ISSUE THREAD

**Issue by maierchr** [Mat931/digitalstrom-homeassistant#18] opened 2024-06-18 13:40 UTC
Hi Mat,

I started working with Homeassistant and Digitalstrom the last days. The integration went smoothly.
And it is pretty impressive to have almost all SmartHome Devices including Digitalstrom under a common hood.

There is only one issue: In my installation there is an Eltako Environment Sensor connected via EnOcean to Digitalstrom. Within Digitalstrom I can see all the values like Temperature, Wind Speed, Rain, ...

In the your integration the values are also shown but will never updated, except the Rain indicator. 
The Other values stay the same as on restart of the plugin.

In my installation I still use the dss10 / dssip setup.

Do you have any suggestion?

Thanks and best regards,
Christoph

**Comment by Mat931** [comment] 2024-06-20 15:18
Hi Christoph,

Can you send me a debug log? You can follow [these steps](https://github.com/Mat931/digitalstrom-homeassistant/blob/main/development.md#getting-a-debug-log).

Thanks

**Comment by maierchr** [comment] 2024-06-21 08:33
[home-assistant_digitalstrom_2024-06-21T08-23-41.106Z.log](https://github.com/user-attachments/files/15924949/home-assistant_digitalstrom_2024-06-21T08-23-41.106Z.log)

Hi Mat,

see attached the requested log-

Thaanks

**Comment by Mat931** [comment] 2024-07-11 18:09
Please test if the problem is fixed in v0.0.11
Thanks

**Comment by maierchr** [comment] 2024-07-12 13:48
It look like the fix solved the problem.

Thanks a lot!
Christoph

**Closed** 2024-07-12 15:05 UTC
